name: Validar Infraestructura P3 (CI)

on:
  push:
    paths:
      - 'P3-iac-integracion-continua/infra/**'
  pull_request:
    paths:
      - 'P3-iac-integracion-continua/infra/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Bicep CLI
        run: az bicep install || (curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64 && chmod +x ./bicep && sudo mv ./bicep /usr/local/bin/bicep)

      - name: Validar sintaxis Bicep
        run: bicep build P3-iac-integracion-continua/infra/main.bicep

      - name: Linter de Bicep
        run: bicep lint P3-iac-integracion-continua/infra/main.bicep